### PR TITLE
Hide window endpoints

### PR DESCRIPTION
**Pull request by braceyourself**
Adds the endpoints for hiding windows from nativephp

### CODE REVIEW

**Comment by mpociot** [comment]
Looks like this PR only contains the dist files, not the actual TS files

**Comment by braceyourself** [comment]
Cool. New to ts but I'll get it sorted for ya shortly.

**Comment by braceyourself** [comment]
Should be all set now. ;)

**Review by simonhamp — APPROVED** [review]
Looks good to go!

**Pull request merged**
