### PR TITLE
Send log event to menubar IPC

### PR DESCRIPTION
**Pull request by JamesHemery**

### CODE REVIEW

**Comment by simonhamp** [comment]
I'm not sure what this PR is aiming to achieve... can you give some context?

**Comment by JamesHemery** [comment]
Currently the menubar render process does not receive logs because it is not part of `state.windows`.

**Comment by simonhamp** [comment]
@JamesHemery can you explain a little more about what this is going to allow you do?

**Comment by JamesHemery** [comment]
@simonhamp My app uses the logs to run some effects. On the other hand, I think it's more consistent to send the logs to the menu bar as well.

**Comment by simonhamp** [comment]
I'm going to allow this because in theory it doesn't hurt.

But I'm not sure about your use-case. I feel like whatever you're trying to achieve needs to be done another way 😅

**Comment by JamesHemery** [comment]
@simonhamp Thx ! In my case this allows to cancel the need for Reverb / Laravel websocket in the simplest cases.

https://github.com/NativePHP/laravel/issues/295#issuecomment-2111968796

This method, defined here as a temporary fix, is, I think, a perfectly suitable method for the simplest use cases. 

On the other hand, it makes sense to send logs to all app windows for consistency :)

**Comment by simonhamp** [comment]
Agreed with the consistency issue. I have a feeling that this won't work in a production build as the `LogWatcher` is meant as a way to support debugging during development...

Have you tested a production build yet?

**Pull request merged**
