### PR TITLE
Add print-to-pdf endpoint

### PR DESCRIPTION
**Pull request by basst85**
Add support for direct print to PDF-file.

### CODE REVIEW

**Comment by mpociot** [comment]
Thank you for the PR. Could you change it so that instead of writing the file, it returns the file as a response?
Then we can return that file in the PHP API and the user can decide what they want to do with it - and potentially save it.

**Comment by basst85** [comment]
> Thank you for the PR. Could you change it so that instead of writing the file, it returns the file as a response? Then we can return that file in the PHP API and the user can decide what they want to do with it - and potentially save it.

Should I return the PDF-data as a base64 encoded string?

**Comment by mpociot** [comment]
Yeah I think this would be the easiest option

**Comment by basst85** [comment]
> Yeah I think this would be the easiest option

Ok 👍 Changed it.

**Comment by mpociot** [comment]
Thank you

**Pull request merged**
